CREATE TABLE IF NOT EXISTS score_result (
    id VARCHAR(32) PRIMARY KEY,
    sport VARCHAR(50) NOT NULL,
    result DOUBLE NOT NULL,
    points INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
